title:            Evaluating Impact
description:      A portfolio documenting the process to develop a digital humanitarian impact evaluation framework. See the "About" page for more information!
url:              http://burnsr77.github.io/EvaluatingImpact
signoff:          Ryan Burns
disqus_shortname: rbuw
baseurl:          /EvaluatingImpact
#facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
#google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /EvaluatingImpact/About
  - name:         Archive
    url:          /EvaluatingImpact/Archive
  - name:         Bibliography
    url:          /EvaluatingImpact/References
  - name:         Contact
    url:          /EvaluatingImpact/Contact
pygments:         true
permalink:        /:categories/:year/:month/:day/:title/
markdown:         rdiscount
rdiscount:
  extensions:     [smart]