title:            Evaluating Impact
description:      A portfolio documenting the process to develop a digital humanitarian impact evaluation framework.
url:              http://burnsr77.github.io/EvaluatingImpact
signoff:          Ryan Burns
disqus_shortname: rbuw
#facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
#google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://muan.co
    external:     true
  - name:         Email
    url:          mailto:hello@muan.co
    external:     true
  - name:         GitHub
    url:          http://github.com/muan
    external:     true
pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]