// Generated by CoffeeScript 1.6.3
//I'm testing the removal of this function to get rid of "A year ago" on the main page.
//jQuery(function() {
//  return $.each($("[data-time]"), function(index, ele) {
//    return $(ele).html(prettyDate(new Date($(this).data("time"))));
//  });
//});
